### ISSUE TITLE
Interstitial ads not working after set testAds false, app crashing

### ISSUE THREAD

**Issue by PratikVekariya4445** [NaiimAb/AdmobAdController#1]
Hi,

i have implemented this controller in app.
When i set .setTestAds(false) , after time interval app is crashing.
I dont want to go next activity so i have commented below 2 lines

`.setAutoMoveActivities(false)`
`.setNextActivityName(activitiesList)`

Now, to show ads i have written like below
 MyApp.adsController.showInterstitial(null, 1);

but app crashing when time comes to display ads

`adsController =new AdsController.Builder(this)
                .setLimitAdmobBannerClicks(true)
                .setBannerMaxClick(2)
                .setBannerDuration(600)
                .setLimitAdmobInterClicks(true)
                .setInterstitialMaxClick(2)
                .setInterstitialDuration(0)
                .setTestAds(false)
                .setLimitAdmobInterClicks(true)
                .setBannerIDList(bannerList)
                .setInterstitialIDList(interList)
                .setLoadingTimer(40)
                .setShowProgressBar(true)
                .setServerURL("")
                //.setAutoMoveActivities(false)
                //.setNextActivityName(activitiesList)

                .build();`

above is my configuration.

And in your video also you set  " MyApp.adsController.showInterstitial(null, 1);" at "36:12" minute.

please help me out! How can i fix this?

**Comment by NaiimAb** [comment]
Hello, thank you for you email. It's true the lib is crashing, I will
modify the error and update. Sorry for that

**Comment by PratikVekariya4445** [comment]
Okay, Thank you. Please let me know when you fix this issue.

**Comment by NaiimAb** [comment]
The issue is fixed. Thanks

**Comment by NaiimAb** [comment]
HEllo Partik,
I've modified the lib and now it's working fine. I've also added facebook
ads to it
I will make another video to implement it. but it should be easy to do it
anyway.
Replace the lib and also the json file
Thank you
